### ISSUE TITLE
User with no phone number cannot mark showing as bought

### ISSUE THREAD

**Issue by lindskogen** [cthdidIT/itbio#189] opened 2018-01-11 23:36 UTC
Currently silent-fails when pressing "Markera bokad"

**Comment by Edholm** [comment] 2018-01-12 04:57
This is by design. Shouldn't silently fail though

**Comment by Edholm** [comment] 2018-01-12 14:47
This is probably related to #21  ;)

**Comment by Edholm** [comment] 2018-01-28 18:43
Fixed in develop branch

**Closed by Edholm** 2018-01-28 18:43 UTC
Labels: Frontend
